name: app
description: Flowtoys Bridge Client Application, find you connect flow !
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.8+8

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  osc:
    git: https://github.com/pq/osc
  rect_getter: ^0.1.0
  flutter_siri_suggestions: #^1.0.2+hotfix1
    path: /Users/neil/Projects/flowtoys/flutter_siri_suggestions
  flutter_reorderable_list: #^0.1.5
    # Patched to support a new version of flutter where the nullOk was deprecated on MediaQuery.of(...)
    path: /Users/neil/Projects/flowtoys/flutter_reorderable_list
  youtube_player_flutter: ^7.0.0+7

  flutter_hsvcolor_picker: #^0.0.1
    path: /Users/neil/Projects/flowtoys/hsvcolor_picker
    # git: 
    #   # Patched to allow for setting the color of the circle on SliderPicker
    #   url: https://github.com/BananaNeil/flutter_hsvcolor_picker
    #   ref: bceccc5bef521184f548608d6dcc90f8dc43280e
  flutter_secure_storage: ^3.3.5
  assets_audio_player: #^2.0.13+1
    path: /Users/neil/Projects/flowtoys/Flutter-AssetsAudioPlayer
  firebase_messaging: ^7.0.3
  # firebase_analytics: ^5.0.16
  flutter_speed_dial: ^1.2.5
  flutter_downloader: ^1.5.1


  percent_indicator: ^2.1.7+2
  bugsnag_crashlytics: ^0.0.7
  connectivity_plus: ^0.8.0
  network_info_plus: ^0.1.1
  flutter_spinkit: ^4.1.2
  email_validator: ^1.0.0
  path_provider: ^1.6.18
  package_info: ^0.4.3+2
  multicast_dns: ^0.2.2
  html_unescape: ^1.0.2
  flutter_blue: #^0.7.3
    # git: git@github.com:pauldemarco/flutter_blue.git
    git: git@github.com:BananaNeil/flutter_blue.git
  url_launcher: ^5.6.0
  fluttertoast: ^7.1.1
  youtube_api: #^0.8.0
    git: https://github.com/SahilKr24/youtube_api
  icon_shadow: ^1.0.1
  validators: ^2.0.1
  event_bus: ^1.1.1
  filesize: ^1.0.4
  json_api: ^4.3.0


  darq: ^0.4.0+1
  quiver: ^2.1.3
  fluro: ^1.7.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/audio/
   - assets/images/
   - assets/config/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
